apiVersion: v1
kind: Service
metadata:
  name: pgpool-svc
spec:
  type: LoadBalancer
  sessionAffinity: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
      nodePort: 30005
  selector:
    app: pgpool
